parameters:
#    perso_user.example.class: Perso\UserBundle\Example

services:
#    perso_user.example:
#        class: %perso_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
