<?php

namespace Perso\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
	public function getComments($page,$nbPerPage) {
		$qb = $this->createQueryBuilder('com');
		/*if (!$admin) {
			$qb
			  ->where('a.statut = :statut')
			  ->setParameter('statut', '1')
			;
		}*/
		$qb
			-> leftJoin('com.article', 'a')
			//-> orderBy('com.date', 'ASC')
			-> addSelect('a')
			-> orderBy("com.date", "DESC")
		;
		$qb
		  // On définit l'annonce à partir de laquelle commencer la liste
		  ->setFirstResult(($page-1) * $nbPerPage)
		  // Ainsi que le nombre d'annonce à afficher sur une page
		  ->setMaxResults($nbPerPage)
		;
		
		return new Paginator($qb, true);
	}
}
